#include <tesseract/motion_planners/descartes/cereal_serialization.h>
#include <tesseract/motion_planners/descartes/cereal_serialization_impl.hpp>

CEREAL_REGISTER_DYNAMIC_INIT(tesseract_motion_planners_descartes_cereal)
