#include <tesseract/motion_planners/trajopt_ifopt/cereal_serialization.h>
#include <tesseract/motion_planners/trajopt_ifopt/cereal_serialization_impl.hpp>

CEREAL_REGISTER_DYNAMIC_INIT(tesseract_motion_planners_trajopt_ifopt_cereal)
