#include <tesseract/time_parameterization/ruckig/cereal_serialization.h>
#include <tesseract/time_parameterization/ruckig/cereal_serialization_impl.hpp>

CEREAL_REGISTER_DYNAMIC_INIT(tesseract_time_parameterization_ruckig_cereal)
